In [ ]:
import json

import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

import sys
import pickle

import re
from pprint import pprint
from scipy import interp
from scipy import sparse
from itertools import cycle

import time

import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import *
from nltk.stem.lancaster import *
from nltk.stem.wordnet import *


from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.preprocessing import label_binarize
from sklearn.preprocessing import MultiLabelBinarizer

from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.linear_model import Perceptron
from sklearn.naive_bayes import MultinomialNB
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score 
from sklearn.metrics import average_precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_curve, auc

In [ ]:
fileName1 = 'C:/Users/M/Documents/ML/IMDB/the-movies-dataset/movies_metadata2.csv'
fileName2 = 'C:/Users/M/Documents/ML/IMDB/tmdb/tmdb_5000_movies.csv' #https://www.kaggle.com/sohier/film-recommendation-engine-converted-to-use-tmdb/data
csv_df = pd.read_csv(fileName2, encoding='iso-8859-1', keep_default_na=False)

In [3]:
csv_df.keys()

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [4]:
df = pd.DataFrame(csv_df, columns=['genres', 'adult', 'budget', 'popularity', 'original_title', 'revenue','runtime', 'vote_average', 'vote_count'])
df.head(10)

,genres,adult,budget,popularity,original_title,revenue,runtime,vote_average,vote_count
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,237000000,150.437577,Avatar,2787965087,162,7.2,11800
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,300000000,139.082615,Pirates of the Caribbean: At World's End,961000000,169,6.9,4500
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,245000000,107.376788,Spectre,880674609,148,6.3,4466
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,250000000,112.312950,The Dark Knight Rises,1084939099,165,7.6,9106
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,260000000,43.926995,John Carter,284139100,132,6.1,2124
5,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",NaN,258000000,115.699814,Spider-Man 3,890871626,139,5.9,3576
6,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",NaN,260000000,48.681969,Tangled,591794936,100,7.4,3330
7,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,280000000,134.279229,Avengers: Age of Ultron,1405403694,141,7.3,6767
8,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,250000000,98.885637,Harry Potter and the Half-Blood Prince,933959197,153,7.4,5293
9,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,250000000,155.790452,Batman v Superman: Dawn of Justice,873260194,151,5.7,7004

In [5]:
df['genres'] = df['genres'].apply(json.loads)

In [6]:
def pipe_flatten_names(keywords):
    return '|'.join([x['name'] for x in keywords])
df['genres'] = df['genres'].apply(pipe_flatten_names)
df['genres']

0        Action|Adventure|Fantasy|Science Fiction
1                        Adventure|Fantasy|Action
2                          Action|Adventure|Crime
3                     Action|Crime|Drama|Thriller
4                Action|Adventure|Science Fiction
5                        Fantasy|Action|Adventure
6                                Animation|Family
7                Action|Adventure|Science Fiction
8                        Adventure|Fantasy|Family
9                        Action|Adventure|Fantasy
10       Adventure|Fantasy|Action|Science Fiction
11                Adventure|Action|Thriller|Crime
12                       Adventure|Fantasy|Action
13                       Action|Adventure|Western
14       Action|Adventure|Fantasy|Science Fiction
15                       Adventure|Family|Fantasy
16               Science Fiction|Action|Adventure
17                       Adventure|Action|Fantasy
18                  Action|Comedy|Science Fiction
19                       Action|Adventure|Fantasy
20                       Action|Adventure|Fantasy
21                               Action|Adventure
22                              Adventure|Fantasy
23                              Adventure|Fantasy
24                         Adventure|Drama|Action
25                         Drama|Romance|Thriller
26               Adventure|Action|Science Fiction
27      Thriller|Action|Adventure|Science Fiction
28      Action|Adventure|Science Fiction|Thriller
29                      Action|Adventure|Thriller
                          ...
4773                                       Comedy
4774                                Drama|Romance
4775                                 Drama|Comedy
4776                                 Comedy|Drama
4777                                        Drama
4778                  Action|Drama|Crime|Thriller
4779                                       Comedy
4780                         Thriller|Crime|Drama
4781                               Comedy|Romance
4782                                 Drama|Family
4783                              Thriller|Horror
4784                         Drama|Comedy|Romance
4785                                        Drama
4786                               Comedy|Romance
4787                     Science Fiction|Thriller
4788                          Horror|Comedy|Crime
4789                                        Drama
4790                                Drama|Foreign
4791                                       Horror
4792                Crime|Horror|Mystery|Thriller
4793                                        Drama
4794                       Thriller|Horror|Comedy
4795                                        Drama
4796               Science Fiction|Drama|Thriller
4797                             Foreign|Thriller
4798                        Action|Crime|Thriller
4799                               Comedy|Romance
4800                Comedy|Drama|Romance|TV Movie
4801
4802                                  Documentary
Name: genres, Length: 4803, dtype: object